### ISSUE TITLE
Root category and store IDs are hard-coded and can be incorrect

### ISSUE THREAD

**Issue by diamondavocado** [Itonomy/magento2-product-visibillitygrid#11]
The root category ID is hard-coded as `2` which results in a site-breaking exception for my store:

`Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with id = 2`

These IDs should not be hard-coded as they will not be the same for all Magento installs, especially if data migration tool has been used.

Same for store ID.

**Comment by benvansteenbergen** [comment]
He @diamondavocado,

Ill fix that in the next version. Thanks for your feedback and sorry for the late response!
