### ISSUE TITLE
Exception in M2.2.4

### ISSUE THREAD

**Issue by joeldavuk** [Itonomy/magento2-product-visibillitygrid#3]
I get this in M2.2.4

`2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS `in_flat_table`, product_name.value AS `name`, product_status.value AS `sta' at line 1, query was: SELECT `main_table`.*, false OR () AS `in_flat_table`, product_name.value AS `name`, product_status.value AS `status`, product_visibility.value AS `visibility`, `category_collection`.`is_online_in_cat`, `category_collection`.* FROM `catalog_product_entity` AS `main_table`
 LEFT JOIN `catalog_product_entity_varchar` AS `product_name` ON product_name.entity_id = main_table.entity_id AND product_name.attribute_id = '71' AND product_name.store_id = '0'
 LEFT JOIN `catalog_product_entity_int` AS `product_status` ON product_status.entity_id = main_table.entity_id AND product_status.attribute_id = '96' AND product_status.store_id = '0'
 LEFT JOIN `catalog_product_entity_int` AS `product_visibility` ON product_visibility.entity_id = main_table.entity_id AND product_visibility.attribute_id = '102' AND product_visibility.store_id = '0'
 LEFT JOIN (SELECT `e`.`entity_id` AS `p_entity_id`, IF(e.entity_id,1,0) AS `is_online_in_cat` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '4' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=5 AND cat_index.visibility IN(2, 4) AND cat_index.category_id='436'
 LEFT JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1
 INNER JOIN `catalog_product_entity_int` AS `at_status_default` ON (`at_status_default`.`entity_id` = `e`.`entity_id`) AND (`at_status_default`.`attribute_id` = '96') AND `at_status_default`.`store_id` = 0
 LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 5) WHERE (IF(at_status.value_id > 0, at_status.value, at_status_default.value) = 1)) AS `category_collection` ON main_table.entity_id = category_collection.p_entity_id ORDER BY main_table.entity_id DESC
 LIMIT 20
Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS `in_flat_table`, product_name.value AS `name`, product_status.value AS `sta' at line 1

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS `in_flat_table`, product_name.value AS `name`, product_status.value AS `sta' at line 1, query was: SELECT `main_table`.*, false OR () AS `in_flat_table`, product_name.value AS `name`, product_status.value AS `status`, product_visibility.value AS `visibility`, `category_collection`.`is_online_in_cat`, `category_collection`.* FROM `catalog_product_entity` AS `main_table`
 LEFT JOIN `catalog_product_entity_varchar` AS `product_name` ON product_name.entity_id = main_table.entity_id AND product_name.attribute_id = '71' AND product_name.store_id = '0'
 LEFT JOIN `catalog_product_entity_int` AS `product_status` ON product_status.entity_id = main_table.entity_id AND product_status.attribute_id = '96' AND product_status.store_id = '0'
 LEFT JOIN `catalog_product_entity_int` AS `product_visibility` ON product_visibility.entity_id = main_table.entity_id AND product_visibility.attribute_id = '102' AND product_visibility.store_id = '0'
 LEFT JOIN (SELECT `e`.`entity_id` AS `p_entity_id`, IF(e.entity_id,1,0) AS `is_online_in_cat` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '4' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=5 AND cat_index.visibility IN(2, 4) AND cat_index.category_id='436'
 LEFT JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1
 INNER JOIN `catalog_product_entity_int` AS `at_status_default` ON (`at_status_default`.`entity_id` = `e`.`entity_id`) AND (`at_status_default`.`attribute_id` = '96') AND `at_status_default`.`store_id` = 0
 LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 5) WHERE (IF(at_status.value_id > 0, at_status.value, at_status_default.value) = 1)) AS `category_collection` ON main_table.entity_id = category_collection.p_entity_id ORDER BY main_table.entity_id DESC
 LIMIT 20
#0 /var/www/bulgin/products/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/bulgin/products/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/bulgin/products/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/bulgin/products/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /var/www/bulgin/products/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /var/www/bulgin/products/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#6 /var/www/bulgin/products/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#8 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/AbstractDb.php(774): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#9 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/AbstractDb.php(670): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#10 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/AbstractDb.php(574): Magento\Framework\Data\Collection\AbstractDb->getData()
#11 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/AbstractDb.php(559): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#12 /var/www/bulgin/products/vendor/magento/module-backend/Block/Widget/Grid/Extended.php(480): Magento\Framework\Data\Collection\AbstractDb->load()
#13 /var/www/bulgin/products/vendor/itonomy/productvisibilitygrid/Block/Adminhtml/ProductVisibilityGrid/Grid.php(84): Magento\Backend\Block\Widget\Grid\Extended->_prepareCollection()
#14 /var/www/bulgin/products/vendor/magento/module-backend/Block/Widget/Grid.php(403): Itonomy\ProductVisibilityGrid\Block\Adminhtml\ProductVisibilityGrid\Grid->_prepareCollection()
#15 /var/www/bulgin/products/vendor/magento/module-backend/Block/Widget/Grid/Extended.php(507): Magento\Backend\Block\Widget\Grid->_prepareGrid()
#16 /var/www/bulgin/products/vendor/magento/module-backend/Block/Widget/Grid.php(468): Magento\Backend\Block\Widget\Grid\Extended->_prepareGrid()
#17 /var/www/bulgin/products/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\Backend\Block\Widget\Grid->_beforeToHtml()
#18 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#19 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('admin.productgr...')
#20 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.productgr...')
#21 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.productgr...')
#22 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.productgr...', true)
#23 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.productgr...')
#24 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#25 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#26 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#27 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#28 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#29 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#30 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#31 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#32 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#33 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#34 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#35 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#36 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#37 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#38 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#39 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#40 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#41 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#42 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#43 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#44 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#45 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#46 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#47 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#48 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#49 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#50 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#51 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#52 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#53 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#54 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#55 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#56 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#57 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#58 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#59 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#60 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#61 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#62 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#63 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#64 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#65 /var/www/bulgin/products/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#66 /var/www/bulgin/products/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#67 /var/www/bulgin/products/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#68 /var/www/bulgin/products/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#69 /var/www/bulgin/products/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#70 /var/www/bulgin/products/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#71 /var/www/bulgin/products/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#72 {main}

Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS `in_flat_table`, product_name.value AS `name`, product_status.value AS `sta' at line 1
#0 /var/www/bulgin/products/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/bulgin/products/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/bulgin/products/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /var/www/bulgin/products/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/bulgin/products/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#5 /var/www/bulgin/products/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#6 /var/www/bulgin/products/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#7 /var/www/bulgin/products/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#8 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#9 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/AbstractDb.php(774): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#10 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/AbstractDb.php(670): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#11 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/AbstractDb.php(574): Magento\Framework\Data\Collection\AbstractDb->getData()
#12 /var/www/bulgin/products/vendor/magento/framework/Data/Collection/AbstractDb.php(559): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#13 /var/www/bulgin/products/vendor/magento/module-backend/Block/Widget/Grid/Extended.php(480): Magento\Framework\Data\Collection\AbstractDb->load()
#14 /var/www/bulgin/products/vendor/itonomy/productvisibilitygrid/Block/Adminhtml/ProductVisibilityGrid/Grid.php(84): Magento\Backend\Block\Widget\Grid\Extended->_prepareCollection()
#15 /var/www/bulgin/products/vendor/magento/module-backend/Block/Widget/Grid.php(403): Itonomy\ProductVisibilityGrid\Block\Adminhtml\ProductVisibilityGrid\Grid->_prepareCollection()
#16 /var/www/bulgin/products/vendor/magento/module-backend/Block/Widget/Grid/Extended.php(507): Magento\Backend\Block\Widget\Grid->_prepareGrid()
#17 /var/www/bulgin/products/vendor/magento/module-backend/Block/Widget/Grid.php(468): Magento\Backend\Block\Widget\Grid\Extended->_prepareGrid()
#18 /var/www/bulgin/products/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\Backend\Block\Widget\Grid->_beforeToHtml()
#19 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('admin.productgr...')
#21 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.productgr...')
#22 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.productgr...')
#23 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.productgr...', true)
#24 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.productgr...')
#25 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#26 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#27 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#28 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#29 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#30 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.col')
#31 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#32 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#33 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#34 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#35 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#36 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#37 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#38 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#39 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#40 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#41 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#42 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#43 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#44 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#45 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#46 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#47 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#48 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#49 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#50 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#51 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#52 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#53 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#54 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#55 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#56 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#57 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#58 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#59 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#60 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#61 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#62 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#63 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#64 /var/www/bulgin/products/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#65 /var/www/bulgin/products/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#66 /var/www/bulgin/products/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#67 /var/www/bulgin/products/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#68 /var/www/bulgin/products/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#69 /var/www/bulgin/products/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#70 /var/www/bulgin/products/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#71 /var/www/bulgin/products/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#72 /var/www/bulgin/products/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#73 {main}`

**Comment by itonomycompany** [comment]
Hey @joeldavuk, can you confirm if this fixed the issue? Thanks in advance!
