### ISSUE TITLE
Is visible in category

### ISSUE THREAD

**Issue by pkjoshi** [Itonomy/magento2-product-visibillitygrid#4]
Hi,
This is not an issue per se, I was facing problem in Magento 2.2.6, that any new products added were not displaying in the frontend.
So I found your extension, installed and in fact it is showing an issue for the products which are not displayed in the frontend.
That is the colum `is visible in Category` is blank for the products which are not visible in frontend, but I couln't find any resolution, how I can address this and what does this mean, as the products are already in the category.
if you can help me understand the usage of this column It will help me address the issue.
I have already cleared caches, reindexing etc. with no help.

thank you.

**Comment by benvansteenbergen** [comment]
Hi @pkjoshi 
The column displays if the product is present in the category collection (yes/no). It should say (no) instead of (blank), that bug will be fixed soon. Can you post me a screenshot with your overview so i can take a look? Thanks, Ben

**Comment by zenomordiante** [comment]
HI, I have the same problem on 2.2.6.
This is screenshot. The products are all Configurable Product

<img width="1182" alt="schermata 2018-12-23 alle 18 07 04" src="https://user-images.githubusercontent.com/1394124/50385912-95aa0f00-06dd-11e9-8ff7-db8501c2fd81.png">

**Comment by zenomordiante** [comment]
Seems there is a Bug on Magento 2.2.6
I have exported and imported all products and now all are visible.

@pkjoshi do you have used Configurable Products using Save & Duplicate?

**Comment by benvansteenbergen** [comment]
Hi, @zenomordiante @pkjoshi 
Fix is provided in new release 1.0.7. Feedback is welcome!

Thanks,

Ben
