### ISSUE TITLE
Compatibility with Magento 2.0.x

### ISSUE THREAD

**Issue by gvillafanetapia** [Itonomy/magento2-product-visibillitygrid#8]
Hello,
I installed the module in Magento 2.0.17 and get the following error:

`[Mon Apr 29 15:51:50.114138 2019] [:error] [pid 18381] [client *********:52547] PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor::unserializeFields() in /***/vendor/magento/framework/Model/ResourceModel/Db/Collection/AbstractCollection.php:604\nStack trace:\n#0 /***/vendor/itonomy/productvisibilitygrid/Model/ResourceModel/ProductVisibilityGrid/Collection.php(427): Magento\\Framework\\Model\\ResourceModel\\Db\\Collection\\AbstractCollection->_afterLoad()\n#1 /***/vendor/magento/framework/Data/Collection/AbstractDb.php(586): Itonomy\\ProductVisibilityGrid\\Model\\ResourceModel\\ProductVisibilityGrid\\Collection->_afterLoad()\n#2 /***/vendor/magento/framework/Data/Collection/AbstractDb.php(557): Magento\\Framework\\Data\\Collection\\AbstractDb->loadWithFilter(false, false)\n#3 /***/vendor/magento/module-backend/Block/Widget/Grid/Extended.php(476): Magento\\Framework\\Data\\Collection\\AbstractDb->load()\n#4 /***/vendor/itonomy/productvisibilitygrid/B in /***/vendor/magento/framework/Model/ResourceModel/Db/Collection/AbstractCollection.php on line 604, referer: https://***/admin/admin/dashboard/index/key/bce0c1fe0e90722a531680abe6f6540f9f59f1bddc20d9c35a438fbc20efc8bf/
`

Also during installation it wouldn't compile. I had to remove ManagerInterface dependency from /itonomy/productvisibilitygrid/Controller/Adminhtml/Index/MassReindex.php and /itonomy/productvisibilitygrid/Controller/Adminhtml/Index/Reindex.php

Any help is appreciated.

Thank you!

**Comment by benvansteenbergen** [comment]
Hey @gvillafanetapia, 
Thanks for using this module! i will check it out soon, because i do not have a 2.0.* instance running.
Ben

**Comment by Beagon** [comment]
Hi @gvillafanetapia,

Thanks for using our module, however we'd like to inform you that we only support Magento version higher than 2.2 since 2.0 has not been supported by Magento themselves since March of 2018 and the support for 2.1 just ended.

Sincerely,

Robin

**Comment by gvillafanetapia** [comment]
OK, thank you.
I'll see to update my instance then.
