### ISSUE TITLE
magento2 php7.1 requesting for token oauth private repos to complete the installation

### ISSUE THREAD

**Issue by merin3** [Itonomy/magento2-product-visibillitygrid#9]
composer require itonomy/productvisibilitygrid
Using version ^1.0 for itonomy/productvisibilitygrid
./composer.json has been updated
Loading composer repositories with package information

Could not fetch https://api.github.com/repos/emizentech/magento2-category-list-widget, please review your configured GitHub OAuth token or enter a new one to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+ip-+2019-06-16+2331
to retrieve a token. It will be stored in "/root/.composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by Beagon** [comment]
Hi @merin3,

This seems to be an issue in your composer.lock. Our module does not require anything else.

Sincerely,

Robin
